name: data
description: Data layer Dart package
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  domain:
    path: ../lib_domain

  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: ^2.3.0
  freezed: ^2.2.0
  json_serializable: ^6.5.1
