name: service
description: Service layer Flutter package
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  data:
    path: ../lib_data

  dio: ^4.0.6
  retrofit: ^3.3.1
  json_annotation: ^4.7.0
  pretty_dio_logger: 1.2.0-beta-1

  shared_preferences: 2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  retrofit_generator: '>=4.0.0 <5.0.0'
  build_runner: '>2.3.0 <4.0.0'
  json_serializable: '>4.4.0'


flutter:
