name: domain
description: Domain layer Dart package
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  bloc: ^8.1.0
  freezed_annotation: ^2.2.0
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  freezed: ^2.2.0
  build_runner: ^2.3.0